# [LAB-05] 4. 결측치 처리

## #01. 준비작업

### 1. 패키지 설치

scikit-learn 패키지의 설치가 필요하다.

In [1]:
!pip install --upgrade scikit-learn

### 2. 라이브러리 참조

In [2]:
import numpy as np
from jussam import load_data
from pandas import DataFrame
from sklearn.impute import SimpleImputer

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/


### 3. 데이터 가져오기

In [3]:
origin = load_data("ref_sample")
origin

📚 데이터 정제를 위한 실습용 데이터


,kor,eng,math,sic
name,,,,
철수,98.000,77,88.000,64.000
영희,88.000,120,62.000,72.000
민철,NaN,70,83.000,79.000
수현,63.000,60,31.000,71.000
호영,75.000,50,90.000,NaN
영호,80.000,88,91.000,72.000
용식,82.000,88,NaN,90.000
나영,90.000,92,81.000,NaN
석영,91.000,90,89.000,80.000


## #02. 결측치 확인하기

### 1. 결측치 여부 확인

각 열에 대해 결측치가 아닐 경우 `False`, 결측치는 `True`로 표시됨

`isna()` 함수도 같은 기능

In [4]:
empty = origin.isnull()
empty

,kor,eng,math,sic
name,,,,
철수,False,False,False,False
영희,False,False,False,False
민철,True,False,False,False
수현,False,False,False,False
호영,False,False,False,True
영호,False,False,False,False
용식,False,False,True,False
나영,False,False,False,True
석영,False,False,False,False


### 2. 각 열별로 결측치의 수를 확인

`isnull()` 혹은 `isna()`의 결과에 대한 합계를 구한다.

`True=1`, `False=0`

In [5]:
empty.sum()

kor     1
eng     0
math    1
sic     2
dtype: int64

## #03. 결측치 소거

### 1. 행 단위 삭제

결측치가 있는 모든 행 삭제 (원본은 변화 없음, 삭제 결과가 리턴됨)

`inplace=True` 파라미터를 적용할 경우 원본에 즉시 반영되고 리턴값 없음

In [6]:
na1 = origin.dropna()
na1

,kor,eng,math,sic
name,,,,
철수,98.000,77,88.000,64.000
영희,88.000,120,62.000,72.000
수현,63.000,60,31.000,71.000
영호,80.000,88,91.000,72.000
석영,91.000,90,89.000,80.000


### 2. 열 단위 삭제

`dropna()` 메서드에 `axis=1` 파라미터를 적용한다. (`기본값=0`)

In [7]:
na2 = origin.dropna(axis=1)
na2

,eng
name,
철수,77
영희,120
민철,70
수현,60
호영,50
영호,88
용식,88
나영,92
석영,90


### 3. 특정 열에 대해서만 결측치가 존재하는 행 삭제

In [8]:
na3 = origin.dropna(subset=['kor'])
na3

,kor,eng,math,sic
name,,,,
철수,98.000,77,88.000,64.000
영희,88.000,120,62.000,72.000
수현,63.000,60,31.000,71.000
호영,75.000,50,90.000,NaN
영호,80.000,88,91.000,72.000
용식,82.000,88,NaN,90.000
나영,90.000,92,81.000,NaN
석영,91.000,90,89.000,80.000


## #04. 결측치 대체

### 1. 고정값으로 대체

모든 결측치를 동일한 값으로 교체

원본은 변화 없음, 삭제결과 리턴됨

`inplace=True`를 적용할 경우 원본에 즉시 반영되고 리턴값 없음

In [9]:
re_df1 = origin.fillna(value=50)
re_df1

,kor,eng,math,sic
name,,,,
철수,98.000,77,88.000,64.000
영희,88.000,120,62.000,72.000
민철,50.000,70,83.000,79.000
수현,63.000,60,31.000,71.000
호영,75.000,50,90.000,50.000
영호,80.000,88,91.000,72.000
용식,82.000,88,50.000,90.000
나영,90.000,92,81.000,50.000
석영,91.000,90,89.000,80.000


### 2. 통계적 값으로 대체 (1) - 결측치를 정제할 규칙을 담고 있는 객체 생성

각 열단위로 평균`(strategy='mean')`을 결측치`(missing_values)`에 지정

strategy 옵션 : mean=평균, median=중앙값, most_frequent: 최빈값(가장 많이 관측되는 수)

> 이 객체의 생성이 결측치를 즉시 처리했다는 것을 의미하는 것은 아니다.

In [10]:
imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr

,"missing_values missing_values: int, float, str, np.nan, None or pandas.NA, default=np.nanThe placeholder for the missing values. All occurrences of`missing_values` will be imputed. For pandas' dataframes withnullable integer dtypes with missing values, `missing_values`can be set to either `np.nan` or `pd.NA`.",nan
,"strategy strategy: str or Callable, default='mean'The imputation strategy.- If ""mean"", then replace missing values using the mean along each column. Can only be used with numeric data.- If ""median"", then replace missing values using the median along each column. Can only be used with numeric data.- If ""most_frequent"", then replace missing using the most frequent value along each column. Can be used with strings or numeric data. If there is more than one such value, only the smallest is returned.- If ""constant"", then replace missing values with fill_value. Can be used with strings or numeric data.- If an instance of Callable, then replace missing values using the scalar statistic returned by running the callable over a dense 1d array containing non-missing values of each column... versionadded:: 0.20 strategy=""constant"" for fixed value imputation... versionadded:: 1.5 strategy=callable for custom value imputation.",'mean'
,"fill_value fill_value: str or numerical value, default=NoneWhen strategy == ""constant"", `fill_value` is used to replace alloccurrences of missing_values. For string or object data types,`fill_value` must be a string.If `None`, `fill_value` will be 0 when imputing numericaldata and ""missing_value"" for strings or object data types.",None
,"copy copy: bool, default=TrueIf True, a copy of X will be created. If False, imputation willbe done in-place whenever possible. Note that, in the following cases,a new copy will always be made, even if `copy=False`:- If `X` is not an array of floating values;- If `X` is encoded as a CSR matrix;- If `add_indicator=True`.",True
,"add_indicator add_indicator: bool, default=FalseIf True, a :class:`MissingIndicator` transform will stack onto outputof the imputer's transform. This allows a predictive estimatorto account for missingness despite imputation. If a feature has nomissing values at fit/train time, the feature won't appear onthe missing indicator even if there are missing values attransform/test time.",False
,"keep_empty_features keep_empty_features: bool, default=FalseIf True, features that consist exclusively of missing values when`fit` is called are returned in results when `transform` is called.The imputed value is always `0` except when `strategy=""constant""`in which case `fill_value` will be used instead... versionadded:: 1.2",False


### 3. 통계적 값으로 대체 (2) - 생성된 규칙을 적용

결측치가 정제된 2차원 배열로 리턴되므로 다시 DataFrame으로 재구성할 필요가 있다.

In [11]:
df_imr = imr.fit_transform(origin.values)
df_imr

array([[ 98.        ,  77.        ,  88.        ,  64.        ],
       [ 88.        , 120.        ,  62.        ,  72.        ],
       [ 83.375     ,  70.        ,  83.        ,  79.        ],
       [ 63.        ,  60.        ,  31.        ,  71.        ],
       [ 75.        ,  50.        ,  90.        ,  75.42857143],
       [ 80.        ,  88.        ,  91.        ,  72.        ],
       [ 82.        ,  88.        ,  76.875     ,  90.        ],
       [ 90.        ,  92.        ,  81.        ,  75.42857143],
       [ 91.        ,  90.        ,  89.        ,  80.        ]])

### 4. 통계적 값으로 대체 (3) - 결측치 정제 결과를 DataFrame으로 재구성

In [12]:
re_df2 = DataFrame(df_imr,
                   index=origin.index,      # 원본의 인덱스
                   columns=origin.columns   # 원본의 컬럼명
                )
re_df2

,kor,eng,math,sic
name,,,,
철수,98.000,77.000,88.000,64.000
영희,88.000,120.000,62.000,72.000
민철,83.375,70.000,83.000,79.000
수현,63.000,60.000,31.000,71.000
호영,75.000,50.000,90.000,75.429
영호,80.000,88.000,91.000,72.000
용식,82.000,88.000,76.875,90.000
나영,90.000,92.000,81.000,75.429
석영,91.000,90.000,89.000,80.000


### 5. 특정 컬럼 하나만 처리하기 (1)- 컬럼의 값만 추출한 후 n행1열로 재구성

- sklearn의 SimpleInputer는 파라미터로 2차 배열을 요구한다.
- 특정 컬럼 하나에 대해서만 결측치 대체를 수행해야 할 경우    
  sklearn의 요구사항에 맞춰 n행 1열로 재구성해야 한다.

In [13]:
reshape = origin['kor'].values.reshape(-1, 1)
reshape

array([[98.],
       [88.],
       [nan],
       [63.],
       [75.],
       [80.],
       [82.],
       [90.],
       [91.]])

### 6. 특정 컬럼의 값 하나만 처리하기 (2) - 결측치 처리하기

In [14]:
reshape_imr = imr.fit_transform(reshape)
reshape_imr

array([[98.   ],
       [88.   ],
       [83.375],
       [63.   ],
       [75.   ],
       [80.   ],
       [82.   ],
       [90.   ],
       [91.   ]])

### 7. 특정 컬럼의 값 하나만 처리하기 (3) - 결측치 처리 결과를 DataFrame의 컬럼에 적용하기

In [15]:
특정컬럼_정제df = origin.copy()
특정컬럼_정제df['kor'] = reshape_imr
특정컬럼_정제df

,kor,eng,math,sic
name,,,,
철수,98.000,77,88.000,64.000
영희,88.000,120,62.000,72.000
민철,83.375,70,83.000,79.000
수현,63.000,60,31.000,71.000
호영,75.000,50,90.000,NaN
영호,80.000,88,91.000,72.000
용식,82.000,88,NaN,90.000
나영,90.000,92,81.000,NaN
석영,91.000,90,89.000,80.000
