# [LAB-02] 2. 다양한 ndarray 유형

## #01. 준비작업

### 1. 라이브러리 참조

In [1]:
import numpy as np

## #02. 2차원 배열

### 1. 2차원 리스트의 ndarray 변환

- 배열의 정보를 확인할 수 있는 프로퍼티가 포함된다.

In [2]:
myarray = np.array([
    [98, 72, 80, 64],
    [88, 90, 80, 72],
    [92, 88, 82, 76]
])

print(myarray)

print("차원크기:", myarray.ndim)
print("차원별 원소수:", myarray.shape)
print("원소의 데이터 타입:", myarray.dtype)

[[98 72 80 64]
 [88 90 80 72]
 [92 88 82 76]]
차원크기: 2
차원별 원소수: (3, 4)
원소의 데이터 타입: int64


### 2. boolean 타입으로 인덱싱

- 조건에 맞는 원소를 1차원으로 반환한다.

In [3]:
bool_array = np.array([
    [True, False, True, False],
    [True, True, True, False],
    [True, True, True, False]
])

# 조건에 맞는 항목만 1차 배열로 추출
# myarray는 이전 실습에서 생성한 2차원 배열
result1 = myarray[bool_array]
result1

array([98, 80, 88, 90, 80, 92, 88, 82])

## #03. 비교식에 의한 검색

### 1. 조건에 맞는 원소를 1차원 배열로 반환한다.

In [4]:
result2 = myarray[myarray >= 80]
result2

array([98, 80, 88, 90, 80, 92, 88, 82])

### 2. `AND` 검색

In [5]:
result3 = myarray[np.logical_and(myarray >= 80, myarray <= 90)]
result3

array([80, 88, 90, 80, 88, 82])

### 3. `OR` 검색

In [6]:
result4 = myarray[np.logical_or(myarray < 80, myarray > 90)]
result4

array([98, 72, 64, 72, 92, 76])

## #04. 정형화된 배열 생성

### 1. 모든 원소가 `0`인 배열

- 파라미터인 [3, 4]는 3행 4열을 의미함

In [7]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2. 모든 원소가 `1`인 배열

- 파라미터인 [3, 4]는 3행 4열을 의미함

In [8]:
np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 3. 모든 원소가 특정값인 배열

- 3행 4열의 배열을 10으로 채움

In [9]:
np.full([3, 4], 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

### 4. 단위행렬

- 대각선 원소가 1이고 그 외에는 0인 배열
  - 파라미터 4는 4행 4열임을 의미함
  - 단위행렬은 항상 가로,세로 크기가 동일

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## #05. 랜덤 배열

### 1. `0`부터 `1`의 범위에서 균등하게 추출하여 N차원 랜덤 배열 생성

- 10개의 값을 갖는 1차원 배열
  - 파라미터는 원소 수를 의미함

In [11]:
np.random.rand(10)

array([0.47972961, 0.4475053 , 0.99283431, 0.45797834, 0.79691129,
       0.72042228, 0.58923268, 0.56920226, 0.9275039 , 0.28920739])

### 2. 4행 3열인 2차원 랜덤 배열 생성

- 파라미터가 두 개인 경우 첫 번째 파라미터는 행, 두 번째 파라미터는 열을 의미

In [12]:
np.random.rand(4, 3)

array([[0.24345906, 0.18889264, 0.2000036 ],
       [0.04020378, 0.05292901, 0.789108  ],
       [0.20888813, 0.28558184, 0.25519483],
       [0.09192636, 0.83513674, 0.67357765]])

## #06. 주어진 범위 안에서 정수값을 갖는 랜덤 배열

### 1. `0`부터 `9`사이의 랜덤값 10개의 원소를 갖는 1차원 배열

In [13]:
np.random.randint(0, 9, 10)

array([0, 7, 2, 7, 3, 0, 5, 0, 1, 0])

### 2. `0`부터 `9`사이의 랜덤값을 갖는 3행 4열의 2차 배열

In [14]:
np.random.randint(0, 9, (3, 4))

array([[8, 0, 6, 7],
       [4, 1, 4, 7],
       [1, 6, 8, 1]])

## #07. 랜덤 시드

### 1. 랜덤 시드(𝑅𝑎𝑛𝑑𝑜𝑚 𝑆𝑒𝑒𝑑)란?

- 난수(𝑟𝑎𝑛𝑑𝑜𝑚 𝑛𝑢𝑚𝑏𝑒𝑟) 는 겉보기엔 무작위지만,    
  실제로는 컴퓨터가 특정 규칙(알고리즘) 에 따라 만들어내는 가짜 무작위값이다.
  - 미리 준비된 수 많은 숫자 묶음 중 하나를 선택하고,    
    선택된 숫자 묶음의 숫자를 순차적으로 꺼내보는 것으로 이해하자.
- 이때 랜덤 시드(Random Seed) 는 그 규칙을 어디서부터 시작할지 정하는 ‘출발점 값’ 이다.
  - 같은 시드를 주면 👉 항상 같은 난수 결과가 나온다. (항상 같은 숫자 묶음을 사용)
  - 다른 시드를 주면 👉 완전히 다른 난수 결과가 나온다. (매번 다른 숫자 묶음을 사용)


### 2. 랜덤 시드를 고정하고 정규 분포를 따르는 랜덤값 생성하기

- `평균 = 0`, `표준편차 = 1`, `배열크기 = 3행 4열`

In [15]:
np.random.seed(1234)
np.random.normal(0, 1, (4, 3))

array([[ 0.47143516, -1.19097569,  1.43270697],
       [-0.3126519 , -0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ,  0.01569637],
       [-2.24268495,  1.15003572,  0.99194602]])

## #08. 표준 정규 분포를 따르는 랜덤 배열

### 1. 원소가 10개인 1차원 배열

In [16]:
np.random.randn(10)

array([ 0.95332413, -2.02125482, -0.33407737,  0.00211836,  0.40545341,
        0.28909194,  1.32115819, -1.54690555, -0.20264632, -0.65596934])

### 2. 4행 3열의 2차원 배열

In [17]:
np.random.randn(4, 3)

array([[ 0.19342138,  0.55343891,  1.31815155],
       [-0.46930528,  0.67555409, -1.81702723],
       [-0.18310854,  1.05896919, -0.39784023],
       [ 0.33743765,  1.04757857,  1.04593826]])

### 3. 정규분포를 직접 설정한 1차원 배열

- 평균은 `0`, 표준편차 `1`의 정규 분포에서 10개의 수를 추출

In [18]:
np.random.normal(0, 1, 10)

array([ 0.86371729, -0.12209157,  0.12471295, -0.32279481,  0.84167471,
        2.39096052,  0.07619959, -0.56644593,  0.03614194, -2.0749776 ])

### 4. 2차원 배열

In [19]:
np.random.normal(0, 1, (4, 3))

array([[ 0.2477922 , -0.89715678, -0.13679483],
       [ 0.01828919,  0.75541398,  0.21526858],
       [ 0.84100879, -1.44581008, -1.40197328],
       [-0.1009182 , -0.54824245, -0.14461951]])