# [LAB-02] 3. ndarray 형태 변환

## #01. 준비작업

### 1. 라이브러리 참조

In [1]:
import numpy as np

## #02. 원소의 데이터 타입변환 [1] - `astype()` 함수 사용

### 1. 실습을 위한 원본 배열 구성

- 배열 원소의 데이터 타입을 변환하는 방법에는 `astype()` 함수를 사용하는 방법과    
  `asarray()` 함수를 사용하는 방법이 있다.

In [2]:
# 0~10 전까지 1씩 증가하는 원소를 갖는 배열 생성
arr1 = np.arange(10)
print("원본배열:", arr1)
print("원본배열의 데이터 타입:", arr1.dtype)

원본배열: [0 1 2 3 4 5 6 7 8 9]
원본배열의 데이터 타입: int64


### 2. 실수(`float`)타입으로 변환

In [3]:
arr2 = arr1.astype('float')
print("형변환 후의 배열:", arr2)
print("변환된 배열의 데이터 타입:", arr2.dtype)

형변환 후의 배열: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
변환된 배열의 데이터 타입: float64


### 3. 문자열(`str`)타입으로 변환

In [4]:
arr3 = arr1.astype('str')
print("형변환 후의 배열:", arr3)
print("변환된 배열의 데이터 타입:", arr3.dtype)

형변환 후의 배열: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
변환된 배열의 데이터 타입: <U21


## #03. 원소의 데이터 타입변환 (2) - `asarray()` 함수 사용

### 1. 원본 배열 구성

In [5]:
# 10~20 전까지 1씩 증가하는 원소를 갖는 배열 생성
arr1 = np.arange(10, 20)
print("원본배열:", arr1)
print("원본배열의 데이터 타입:", arr1.dtype)

원본배열: [10 11 12 13 14 15 16 17 18 19]
원본배열의 데이터 타입: int64


### 2. 실수(`float`)타입으로 변환

- 변환할 원본 배열과 변환될 타입(dtype)을 파라미터로 설정한다.

In [6]:
arr2 = np.asarray(arr1, dtype='float')
print("형변환 후의 배열:", arr2)
print("변환된 배열의 데이터 타입:", arr2.dtype)

형변환 후의 배열: [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
변환된 배열의 데이터 타입: float64


### 3. 문자열(`str`)타입으로 변환

In [7]:
arr3 = np.asarray(arr1, dtype='str')
print("형변환 후의 배열:", arr3)
print("변환된 배열의 데이터 타입:", arr3.dtype)

형변환 후의 배열: ['10' '11' '12' '13' '14' '15' '16' '17' '18' '19']
변환된 배열의 데이터 타입: <U21


## #04. reshape() 함수를 사용한 차원 변환

### 1. `1~20`전 까지 1씩 증가하는 값을 갖는 1차원 배열 생성


In [8]:
origin = np.arange(20)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### 2. 1차원 배열을 4행 5열의 2차원 배열로 변환

- `reshape(행,열)` 메서드를 사용한다.

In [9]:
x = origin.reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 3. 변환할 수 없는 경우

- `행,열`로 재구성했을 경우 원소의 수가 남거나 모자라서는 안된다.
- 아래의 경우는 원소의 수가 3행,7열로 구성될 수 없기 때문에 에러가 발생함

In [10]:
origin.reshape(3, 7)

ValueError: cannot reshape array of size 20 into shape (3,7)

## #05. reshape() 함수를 사용한 차원 축소

### 1. 원본 배열 구성

In [11]:
origin = np.array([[ 0,  1,  2,  3,  4],
                   [ 5,  6,  7,  8,  9],
                   [10, 11, 12, 13, 14],
                   [15, 16, 17, 18, 19]])
origin

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 2. 1차원 배열로 축소 하기

- reshape() 함수에 하나의 파라미터만 전달할 경우 열의 수를 의미한다.
- 여기서는 20개의 열로 재구성하라는 의미이므로 1개의 행을 갖게 된다.
  - 결국 20개의 원소를 갖는 1차 배열로 재구성된다.

In [12]:
y = origin.reshape(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### 3. 원소의 수 계산 후 1차원 배열로 축소하기

- 1차원으로 변환할 경우 일일이 원소의 수를 카운트하기는 번거로우므로 `shape`를 구해서 활용한다.

In [13]:
rows, cols = origin.shape
rows, cols

(4, 5)

In [14]:
z = origin.reshape(rows * cols)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## #06. `reshape()` 함수에서 `-1`의 의미

### `n`개라는 의미로 이해하자

- `reshape()`를 활용하는 경우를 보다 보면 입력 파라미터로 `-1`이 들어간 경우가 종종 있다.
- `reshape()`의 `-1`이 의미하는 바는, 변경된 배열의 `-1` 위치의 차원은 “원래 배열의 길이와 남은 차원으로 부터 추정”이 된다는 뜻이다.

### 1. `reshape(-1,정수)` : 실습을 위한 원본 배열 생성

In [15]:
origin = np.array([[ 0,  1,  2,  3],
                   [ 4,  5,  6,  7],
                   [ 8,  9, 10, 11]])
origin

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 2. `reshape(-1,정수)` : 행의 수에 관계 없이 1열을 갖는 2차원 배열

In [23]:
x = origin.reshape(-1, 1)
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

### 3. `reshape(-1,정수)` :  행의 수에 관계 없이 2열을 갖는 2차원 배열

In [17]:
y = origin.reshape(-1, 2)
y

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

### 4. `reshape(정수, -1)` : 실습을 위한 원본 배열 생성

In [18]:
origin = np.arange(12)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 5. `reshape(정수, -1)` : 열의 수에 관계 없이 1행을 갖는 2차원 배열로 재구성

In [19]:
x = origin.reshape(1, -1)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

### 6. `reshape(정수, -1)` : 열의 수에 관계 없이 2행을 갖는 2차원 배열로 재구성

In [20]:
y = origin.reshape(2, -1)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### 7. `reshape(-1)` 인 경우

- 행의 수에 상관 없이 𝑛개의 열로 재구성함 --> 1차원 배열로 변환하라는 의미

In [21]:
# 원본 배열
origin = np.array([[ 0,  1,  2,  3,  4,  5],
                   [ 6,  7,  8,  9, 10, 11]])
print(origin)

# 1차 배열로 재배치
x = origin.reshape(-1)
x

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])