# [LAB-02] 3. ndarray 형태 변환 

## #01. 준비작업 

### 1. 라이브러리 참조 

In [ ]:
import numpy as np

## #02. 원소의 데이터 타입 변환[1] astype() 함수 사용 

### 실습을 위한 원본 배열 구성 

In [2]:
import numpy as np

In [4]:
# 0~10 전까지 1씩 증가하는 원소를 갖는 배열 생성 
arr1 = np.arange(10)
print("원본배열:", arr1)
print("원본배열의 데이터 타입:", arr1.dtype)

원본배열: [0 1 2 3 4 5 6 7 8 9]
원본배열의 데이터 타입: int64


In [5]:
# 실수(float)타입으로 변환 
arr2 = arr1.astype('float')
print("형변환 후의 배열:", arr2)
print("변환된 배열의 데이터 타입:", arr2.dtype)

형변환 후의 배열: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
변환된 배열의 데이터 타입: float64


In [6]:
# 3. 문자열(str)타입으로 변환
arr3 = arr1.astype('str')
print("형변환 후의 배열:", arr3)
print("변환된 배열의 데이터 타입:", arr3.dtype)

형변환 후의 배열: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
변환된 배열의 데이터 타입: <U21


## #03. 원소의 데이터 타입 변환[2] - asarray()함수 사용

In [7]:
# 1. 원본 배열 구성 
# 10~20 전까지 1씩 증가하는 원소를 갖는 배열 생성 
arr1 = np.arange(10, 20)
print("원본배열:", arr1)
print("원본배열의 데이터 타입:", arr1.dtype)

원본배열: [10 11 12 13 14 15 16 17 18 19]
원본배열의 데이터 타입: int64


In [8]:
# 2. 실수(float)타입으로 변환
# 변환할 원본 배열과 변환될 타입(dtype)을 파라미터로 설정한다.
arr2 = np.asarray(arr1, dtype='float')
print("형변환 후의 배열:", arr2)
print("변환된 배열의 데이터 타입:", arr2.dtype)

형변환 후의 배열: [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
변환된 배열의 데이터 타입: float64


In [9]:
# 3. 문자열(str)타입으로 변환
arr3 = np.asarray(arr1, dtype='str')
print("형변환 후의 배열:", arr3)
print("변환된 배열의 데이터 타입:", arr3.dtype)

형변환 후의 배열: ['10' '11' '12' '13' '14' '15' '16' '17' '18' '19']
변환된 배열의 데이터 타입: <U21


In [ ]:
## # 04.reshape()함수를 사용한 차원 변환
# 1.  1~20전까지 1씩 증가하는 값을 갖는 1차원 배열 생성 
origin = np.arange(20)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
# 2. 1차원 배열을 4행 5열의 2차원 배열로 변환 
# reshape(행, 열) 메서드를 사용한다. 
x = origin.reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
# 3. 변환할 수 없는 경우 
# origin.reshape(3,7)

In [14]:
## # 05. reshape()함수를 사용한 차원 축소 
# 1. 원본 배열 구성 
origin = np.array([[0,1,2,3,4],
                   [5,6,7,8,9],
                   [10,11,12,13,14],
                   [15,16,17,18,19]])
origin

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
# 2. 1차원 축소하기 
y = origin.reshape(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
#3. 원소의 수 계산 후 1차원 배열로 축소하기 
rows, cols = origin.shape
rows, cols

(4, 5)

In [17]:
z = origin.reshape(rows * cols)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
## # 06. reshape()함수에서 - 1의 의미
# 1. reshape(-1, 정수) : 실습을 위한 원본 배열 생성 
origin = np.array([[0,1,2,3],
                   [4,5,6,7],
                   [8,9,10,11]])
origin

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
# 1. reshape(-1, 정수): 행의 수에 관계없이 1열을 갖는 2차원 배열 
x = origin.reshape(-1,1)
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [21]:
# 2. reshape(-1,정수): 행의 수에 관계없이 2열을 갖는 2차원 배열 
y = origin.reshape(-1,2)
y

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [22]:
# 4. reshape(정수, -1): 실습을 위한 원본 배열 생성 
origin = np.arange(12)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
# 5. reshape(정수, -1): 열의 수에 관계없이 1행을 갖는 2차원 배열로 재구성
x = origin.reshape(1,-1)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [24]:
# 6. reshape(정수, -1): 열의 수에 관계없이 2행을 갖는 2차원 배열로 재구성 
y = origin.reshape(2,-1)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [25]:
#7. reshape(-1)인 경우 
# 행의 수에 상관없이 n개의 열로 재구성함 -> 1차원 배열로 변환하라는 의미 

# 원본 배열 
origin = np.array([[0,1,2,3,4,5], 
                   [6,7,8,9,10,11]])
print(origin)

# 1차 배열로 재배치 
x = origin.reshape(-1)
x

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## # 1. 연습문제 
### 0부터 11까지 정수를 가지는 배열을 생성하시오
### 이 배열을 실수형(float)으로 변환하시오
### 변환된 배열을 2행 6열 구조로 재배치 하시오
### 이후, 열의 수에 관계없이 3행으로 자동 변환되도록 reshape()함수를 이용하시오
### 마지막으로 1차원 배열로 축소하여 결과를 출력하시오

In [ ]:
exam1 = np.ndarray([0,1,2,3,4,5,6,7,8,9,10,11]) 
exam1.int