# [LAB-02] 2. 다양한 ndarray 유형

## # 01. 준비작업 

### 1. 라이브러리 참조 

In [2]:
import numpy as np

## #02. 2차원 배열 
### 1. 2차원 리스트의 ndarray 변환
#### - 배열의 정보를 확인할 수 있는 프로퍼티가 포함된다

In [3]:
myarray = np.array([
    [98, 72, 80, 64],
    [88, 90, 80, 72], 
    [92, 88, 82, 76]
])

print(myarray)

print("차원크기:", myarray.ndim)
print("차원별 원소수", myarray.shape)
print("원소의 데이터 타입:", myarray.dtype)

[[98 72 80 64]
 [88 90 80 72]
 [92 88 82 76]]
차원크기: 2
차원별 원소수 (3, 4)
원소의 데이터 타입: int64


### 2. boolean 타입으로 인덱싱 
#### - 조건에 맞는 원소를 1차원 배열로 반환한다.

In [4]:
bool_array = np.array([
    [True, False, True, False],
    [True, True, True, False],
    [True, True, True, False]
])

# 조건에 맞는 항목만 1차 배열로 추출
# myarray는 이전 실습에서 생성한 2차원 배열 
result1 = myarray[bool_array]
result1

array([98, 80, 88, 90, 80, 92, 88, 82])

## #03. 비교식에 의한 검색 

In [5]:
# 1. 조건에 맞는 원소를 1차원 배열로 반환한다. 
result2 = myarray[myarray >=80]
result2

array([98, 80, 88, 90, 80, 92, 88, 82])

In [6]:
# 2. AND 검색 
result3 = myarray[np.logical_and(myarray >=80, myarray <=90)]
result3

array([80, 88, 90, 80, 88, 82])

In [7]:
# 3. OR 검색
result4 = myarray[np.logical_or(myarray <80, myarray > 90)]
result4

array([98, 72, 64, 72, 92, 76])

## #04.정형화된 배열 생성


In [8]:
# 1. 모든 원소가 0인 배열
## 파라미터인 [3,4]는 3행 4열을 의미함 
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# 2. 모든 원소가 1인 배열 
# 파라미터인 [3,4]는 3행 4열을 의미함 
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
# 3. 모든 원소가 특정 값인 배열 
# 3행 4열의 배열을 10으로 채움 
np.full([3,4], 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [11]:
# 4. 단위 행렬 
# 대각선 원소가 1이고 그외에는 0인 배열 
# 파라미터 4는 4행 4열임을 의미함 
# 단위행렬은 항상 가로, 세로 크기가 동일 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## #05. 랜덤 배열 



In [12]:
# 1. 0부터 1의 범위에서 균등하게 추출하여 N차원 랜덤 배열 생성 
# 10개의 값을 갖는 1차원 배열, 파라미터는 원소 수를 의미함
np.random.rand(10)


array([0.11160335, 0.83066434, 0.79833823, 0.55632951, 0.87341626,
       0.62129205, 0.2253481 , 0.58643333, 0.80817901, 0.62518025])

In [13]:
# 2. 4행 3열인 2차원 랜덤 배열 생성
# 파라미터가 두개인 경우 첫번째 파라미터는 행, 두번째 파라미터는 열을 의미 
np.random.rand(4,3)

array([[0.13710433, 0.76072675, 0.47725438],
       [0.5077342 , 0.67558462, 0.3057602 ],
       [0.64120649, 0.57773917, 0.62511144],
       [0.89212712, 0.63306852, 0.40931209]])

## #06. 주어진 범위 안에서 정수값을 갖는 랜덤 배열 

In [14]:
# 1. 0부터 9사이의 랜덤값 10개의 원소를 갖는 1차원 배열
np.random.randint(0, 9, 10)

array([7, 0, 4, 7, 2, 0, 1, 1, 5, 0], dtype=int32)

In [15]:
# 0부터 9사이의 랜덤 값을 갖는 3행 4열의 2차 배열 
np.random.randint(0, 9, (3,4))

array([[3, 4, 0, 8],
       [5, 8, 4, 4],
       [4, 2, 2, 0]], dtype=int32)

## # 07. 랜덤 시드
#### 1. 랜덤 시드(Random Seed)란?
* 난수(random number)는 겉보기엔 무작위지만, 실제로는 컴퓨터가 특정규칙(알고리즘)에 따라 만들어내는 가짜 무작위 값이다. 
    * 미리 준비된 수 많은 숫자 묶음 중 하나를 선택하고, 선택된 숫자 묶음의 숫자를 순차적으로 꺼내보는 것으로 이해하자
#### 2. 랜덤 시드를 고정하고 정규 분포를 따르는 랜덤값 생성하기
* 이때 랜덤 시드(Random Seed)는 그 규칙을 어디서부터 시작할지 정하는 '출발점 값'이다.
    * 같은 시드를 주면, 항상 같은 난수 결과가 나온다. (항상 같은 숫자 묶음을 사용)
    * 다른 시드를 주면, 완전히 다른 난수 결과가 나온다.(매번 다른 숫자 묶음을 사용)

In [16]:
# 랜덤 시드를 고정하고 정규분포를 따르는 랜덤값 생성하기
np.random.seed(1234)
np.random.normal(0,1,(4,3))

array([[ 0.47143516, -1.19097569,  1.43270697],
       [-0.3126519 , -0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ,  0.01569637],
       [-2.24268495,  1.15003572,  0.99194602]])

## #08. 표준정규분포를 따르는 랜덤 배열 

In [17]:
# 1. 원소가 10개인 1차원 배열 
np.random.randn(10)

array([ 0.95332413, -2.02125482, -0.33407737,  0.00211836,  0.40545341,
        0.28909194,  1.32115819, -1.54690555, -0.20264632, -0.65596934])

In [18]:
# 2. 4행 3열의 2차원 배열 
np.random.randn(4,3)

array([[ 0.19342138,  0.55343891,  1.31815155],
       [-0.46930528,  0.67555409, -1.81702723],
       [-0.18310854,  1.05896919, -0.39784023],
       [ 0.33743765,  1.04757857,  1.04593826]])

In [19]:
# 3. 정규분포를 직접 설정한 1차원 배열 
np.random.normal(0,1,10)

array([ 0.86371729, -0.12209157,  0.12471295, -0.32279481,  0.84167471,
        2.39096052,  0.07619959, -0.56644593,  0.03614194, -2.0749776 ])

In [20]:
# 4. 2차원 배열 
np.random.normal(0,1,(4,3))

array([[ 0.2477922 , -0.89715678, -0.13679483],
       [ 0.01828919,  0.75541398,  0.21526858],
       [ 0.84100879, -1.44581008, -1.40197328],
       [-0.1009182 , -0.54824245, -0.14461951]])

## #1. 연습문제 - 성적 처리 시스템 만들기 

정수형 ndarray로 변환하시오
점수가 80점 이상인 학생의 점수만 추출하여 출력하시오

모든 학생에게 다음 기준으로 학점을 부여하고 결과를 출력하시오.

90점이상 A / 80점 이상 B / 70점 이상 C / 그 외 F 

In [35]:
import numpy as np
score = np.array([72.5, 88.0, 91.5, 67.0, 80.0, 59.5])


print("원본 점수:", score)

원본 점수: [72.5 88.  91.5 67.  80.  59.5]


In [38]:
result1 = score[score >= 80]

print("80점 이상:", result1)

80점 이상: [88.  91.5 80. ]


In [ ]:
#  float → int 변환은 **반올림이 아니라 버림(truncate)**

In [59]:
result1 = np.array(score, dtype='int')
print("원본 점수:", result1)

print("80점 이상:", result1[result1 >= 80])

원본 점수: [72 88 91 67 80 59]
80점 이상: [88 91 80]


In [49]:
score_int = score.astype(int)
print("원본 점수:", score_int)

result = score_int[score_int >= 80]
print("80점 이상:", result)

원본 점수: [72 88 91 67 80 59]
80점 이상: [88 91 80]


In [50]:
exam1 = [ (score>=90 ),
         (score >=80), 
         (score >=70)]
value = ['A', 'B', 'C']

result = np.select(exam1, value, default='F')
print("학점 결과", result)

학점 결과 ['C' 'B' 'A' 'F' 'B' 'F']


In [51]:
grades = np.where(score_int>=90, 'A',
          np.where(score_int>=80, 'B',
          np.where(score_int>=70, 'C', 'F')))

## #2. 연습문제 - AI 교육생 점수 데이터 점검하기 

1. 평균 75, 표준편차가 5인 정규분포를 따르는 랜덤 점수 데이터를 3행 4열 배열로 생성
단, 결과가 재현되도록 랜덤 시드를 100으로 고정

2. 생성된 점수 중 80점 이상인 항목만 추출
3. 점수가 저장된 배열의 차원(ndim), 형태(shape), 데이터 타입(dtype)을 각각 출력하시오. 

In [52]:
np.random.seed(100)
exam2 = np.random.normal(75, 5, (3,4))
exam2

array([[66.25117263, 76.71340202, 80.76517901, 73.73781982],
       [79.90660393, 77.57109421, 76.10589835, 69.64978335],
       [74.05252085, 76.27500722, 72.70986507, 77.17581744]])

In [53]:
print( "80점 이상 점수:", exam2[exam2 >=80])

80점 이상 점수: [80.76517901]


In [54]:
type(exam2)

numpy.ndarray

In [55]:
print("차원:", exam2.ndim)

차원: 2


In [56]:
print("형태:", exam2.shape)

형태: (3, 4)


In [57]:
print("데이터 타입:", exam2.dtype)

데이터 타입: float64
