# [LAB-02] 5. 기술 통계량의 이해(2) 

## #01. 준비작업 

### 1. 라이브러리 참조 

In [1]:
import numpy as np

### 2. 실습을 위한 샘플 데이터 준비

In [2]:
point = np.array([100, 91, 89, 86, 84, 79, 78, 77, 74, 71, 69, 66, 65, 60, 58, 57, 55])

point

array([100,  91,  89,  86,  84,  79,  78,  77,  74,  71,  69,  66,  65,
        60,  58,  57,  55])

## #02. Numpy의 histogram : 도수 분포도 

### 1. 5개의 구간으로 나누기 

In [3]:
hist, bins = np.histogram(point, 5)
print("구간별 데이터 수: ", hist)
print("구간 경계: ", bins)

구간별 데이터 수:  [4 4 4 3 2]
구간 경계:  [ 55.  64.  73.  82.  91. 100.]


### 2. 도수 분포표 구성

In [4]:
s = len(hist)
for i in range(0, s): 
    if i + 1 <s :
        tpl = "%d이상 %d미만 : %d개"
    else: 
        tpl = "%d이상 %d이하 : %d개"

    print(tpl % (bins[i], bins[i+1], hist[i]))

55이상 64미만 : 4개
64이상 73미만 : 4개
73이상 82미만 : 4개
82이상 91미만 : 3개
91이상 100이하 : 2개


### 3. 데이터 구간을 직접 정의하기 

In [5]:
hist, bins = np.histogram(point, [50,60,70,80,90,100])
print("구간별 데이터 수: ", hist)
print("구간 경계: ", bins)

구간별 데이터 수:  [3 4 5 3 2]
구간 경계:  [ 50  60  70  80  90 100]


## #03. 도수의 종류

### 1. 절대도수
### 2. 상대도수 

In [6]:
relative_freq = hist /np.sum(hist)
relative_freq

array([0.17647059, 0.23529412, 0.29411765, 0.17647059, 0.11764706])

### 3. 누적 도수

In [7]:
cum_freq = []

previous = 0 

for i in hist:
    previous += i
    cum_freq.append(previous)

cum_freq

[np.int64(3), np.int64(7), np.int64(12), np.int64(15), np.int64(17)]

## #1. 연습문제 - 일일 판매량 데이터 분석 

In [8]:
sales = np.array([18,25,33,21,28,40,15,3,9,17,22,29,38,45, 11,6, 31, 24, 27, 35, 12, 39, 42, 7, 2, 20, 34, 26, 30])

hist, bins = np.histogram(sales, [0, 10,20,30,40,50])
print("구간별 데이터 수 ", hist)
print("구간 경계", bins)

구간별 데이터 수  [5 5 9 7 3]
구간 경계 [ 0 10 20 30 40 50]


In [9]:
s = len(hist)
for i in range(0, s): 
    if i + 1 < s :
        tpl = "%d이상 %d미만 : %d개"
    else: 
        tpl = "%d이상 %d이하 : %d개"

    print(tpl % (bins[i], bins[i+1], hist[i]))

0이상 10미만 : 5개
10이상 20미만 : 5개
20이상 30미만 : 9개
30이상 40미만 : 7개
40이상 50이하 : 3개


In [10]:
relative_freq = hist / np.sum(hist)
relative_freq

array([0.17241379, 0.17241379, 0.31034483, 0.24137931, 0.10344828])

In [11]:
cum_freq = []

previous = 0 

for i in hist: 
    previous += i 
    cum_freq.append(previous)

cum_freq

[np.int64(5), np.int64(10), np.int64(19), np.int64(26), np.int64(29)]

In [12]:
sales = np.array([1,2,3,4,5,6,7,8,9,10])
hist, bins = np.histogram(sales, [1,3,5,7,9])
print("구간별 데이터 수:", hist)
print("구간 경계:", bins)

s = len(hist)
for i in range(0, s):
    if i + 1 <s :
        tpl = "%d이상 %d미만 : %d개"    
    else: 
        tpl = "%d이상 %d이하 : %d개"
    print(tpl % (bins[i], bins[i+1], hist[i]))


구간별 데이터 수: [2 2 2 3]
구간 경계: [1 3 5 7 9]
1이상 3미만 : 2개
3이상 5미만 : 2개
5이상 7미만 : 2개
7이상 9이하 : 3개


In [13]:
point = np.array([100, 91, 89, 86, 84, 79, 78, 77, 74, 71, 69, 66, 65, 60, 58, 57, 55])

point

# np.histogram(데이터, 구간수) 함수를 사용하여, 구간별 데이터수(hist)와 구간 범위(bins)를 리턴 받는다. 

hist, bins = np.histogram(point, 5)
print("구간별 데이터 수: ", hist)
print("구간 경계: ", bins)

s = len(hist)
for i in range(0, s):
    if i+1 < s:
        tpl = "%d이상 %d미만: %d개" 
    else: 
        tpl = "%d이상 %d이하: %d개" 

    print(tpl % (bins[i], bins[i+1], hist[i]))

hist, bins = np.histogram(point, [50, 60, 70, 80, 90, 100])
print("구간별 데이터 수: ", hist)
print("구간 경계: ", bins)

relative_freq = hist / np.sum(hist)
relative_freq



구간별 데이터 수:  [4 4 4 3 2]
구간 경계:  [ 55.  64.  73.  82.  91. 100.]
55이상 64미만: 4개
64이상 73미만: 4개
73이상 82미만: 4개
82이상 91미만: 3개
91이상 100이하: 2개
구간별 데이터 수:  [3 4 5 3 2]
구간 경계:  [ 50  60  70  80  90 100]


array([0.17647059, 0.23529412, 0.29411765, 0.17647059, 0.11764706])

In [14]:
cum_freq = []

previous = 0

for i in hist:
    previous += i 
    cum_freq.append(previous)

cum_freq

[np.int64(3), np.int64(7), np.int64(12), np.int64(15), np.int64(17)]

In [15]:
import numpy as np

# 1. numpy 배열 생성
sales_data = np.array([18, 25, 33, 21, 28, 40, 15, 3, 9, 17, 22, 29, 38, 45, 11, 6, 31, 24, 27, 35, 12, 19, 39, 42, 7, 2, 20, 34, 26, 30])

# 2. 도수분포 분석
bins = [0, 10, 20, 30, 40, 50]
hist, bin_edges = np.histogram(sales_data, bins=bins)

# 상대도수 계산
relative_freq = hist / np.sum(hist)

# 누적도수 계산
cum_freq = []
previous = 0
for h in hist:
    previous += h
    cum_freq.append(previous)

# 3. 도수분포표 출력
print("--- 일일 판매량 분석 ---")

for i in range(len(hist)):
    # 구간의 마지막인지 확인하여 레이블 조정
    if i == len(hist) - 1:
        label = f"{bin_edges[i]} 이상 {bin_edges[i+1]} 이하"
    else:
        label = f"{bin_edges[i]} 이상 {bin_edges[i+1]} 미만"

    # 출력 템플릿
    tpl = f"구간: {label} | 절대도수: {hist[i]} | 상대도수: {relative_freq[i]:.3f} | 누적도수: {cum_freq[i]}"
    print(tpl)

--- 일일 판매량 분석 ---
구간: 0 이상 10 미만 | 절대도수: 5 | 상대도수: 0.167 | 누적도수: 5
구간: 10 이상 20 미만 | 절대도수: 6 | 상대도수: 0.200 | 누적도수: 11
구간: 20 이상 30 미만 | 절대도수: 9 | 상대도수: 0.300 | 누적도수: 20
구간: 30 이상 40 미만 | 절대도수: 7 | 상대도수: 0.233 | 누적도수: 27
구간: 40 이상 50 이하 | 절대도수: 3 | 상대도수: 0.100 | 누적도수: 30
