# [LAB-02] 4. 기술 통계량의 이해(1) 

## #01. 기술통계량의 이해 

### 1. 준비작업

In [1]:
# 1. 라이브러리 참조 
import numpy as np 

# 2. 샘플 데이터 생성 
myarr = np.array([98, 72, 80, 64, 88, 65, 79, 59, 81, 74])
myarr

array([98, 72, 80, 64, 88, 65, 79, 59, 81, 74])

## #02.데이터의 위치, 분포를 나타내는 기술 통계량 

In [2]:
# 1. 총 도수 
print("총 도수", len(myarr))

# 2. 최대(max), 최소(min), 합계(sum)
print("최대값:", np.max(myarr))
print("최소값:", np.min(myarr))
print("합계:", np.sum(myarr))

총 도수 10
최대값: 98
최소값: 59
합계: 760


In [3]:
# 3. 평균 
print("평균(average):", np.average(myarr))
print("평균(mean):", np.mean(myarr))

평균(average): 76.0
평균(mean): 76.0


In [4]:
# 4. 중앙값(직접 구하기)
size = len(myarr) # 전체 데이터 수 
sorted_arr = np.sort(myarr) # 순서대로 정렬
print("정렬:", sorted_arr)

# 짝수인 경우 가운데 두 수의 평균 
if size % 2==0 :
    p=(size //2) -1 #인덱스가 0부터 시작하므로 -1
    q = p+1 
    median = (sorted_arr[p] + sorted_arr[q])/2
else:
    p = size //2 
    median = sorted_arr[p]

print("중앙값:", median)

정렬: [59 64 65 72 74 79 80 81 88 98]
중앙값: 76.5


In [5]:
# 5. 중앙값(Numpy 사용)
print( "중앙값:", np.median(myarr))

중앙값: 76.5


In [7]:
# 6. 1사분위 수 
x = np.sort(myarr) # 데이터 정렬 
n = len(x) #총 도수 
q1_pos = (n-1)*0.25 # 위치 계산 (p)
i = int(np.floor(q1_pos)) #아래쪽 인덱스(i)
f = q1_pos - i #보간비율(f)

# 보간(interpolation)
Q1 = x[i] + f* (x[i+1] - x[i])
print("직접 계산한 1사분위 수 (Q1):", Q1)

# numpy 내장 함수와 비교
print("Numpy로 계산한 1사분위수:", np.quantile(myarr, 0.25))

직접 계산한 1사분위 수 (Q1): 66.75
Numpy로 계산한 1사분위수: 66.75


In [8]:
# 7. 3사분위 수 
x = np.sort(myarr) # 데이터 정렬 
n = len(x) # 총 도수
q3_pos = (n-1) *0.75 # 위치 계산 (p)
i = int(np.floor(q3_pos)) #아래쪽 인덱스(i) 
f = q3_pos -i # 보간비율(f)

# 보간 (interpolation)
Q3 = x[i] + f* (x[i+1] -x[i])
print("직접 계산한 3사분위수 (Q3):", Q3)

# numpy 내장 함수와 비교 
print("Numpy로 계산한 3사분위수:", np.quantile(myarr, 0.75))

직접 계산한 3사분위수 (Q3): 80.75
Numpy로 계산한 3사분위수: 80.75


## #04. 데이터의 범위, 산포를 나타내는 기초 통계량 

In [9]:
# 1. 데이터 구간(Range)
print("데이터 구간:", np.max(myarr) - np.min(myarr))

데이터 구간: 39


In [10]:
# 2. 사분위 수 구간 (IQR)
q3 = np.quantile(myarr, 0.75) 
q1 = np.quantile(myarr, 0.25)
print("사분위수 구간(IQR):", q3 - q1)

사분위수 구간(IQR): 14.0


In [11]:
# 3. 분산, 표준편차 
print("분산:", np.var(myarr))
print("표준편차:", np.std(myarr))

분산: 125.2
표준편차: 11.189280584559492


## #05. 2차원 배열의 기술 통계량 

In [12]:
# 1. 각 열끼리 연산 (세로 연산)
mydata = np.array([[98, 72, 80, 64, 88], 
                   [65, 79, 59, 81, 74]])

s1 = np.sum(mydata, axis =0) 
print(type(s1))
s1

<class 'numpy.ndarray'>


array([163, 151, 139, 145, 162])

In [13]:
# 1. 각 행끼리 연산 (가로 연산)
mydata = np.array([[98, 72, 80, 64, 88], 
                   [65, 79, 59, 81, 74]])

s1 = np.sum(mydata, axis =1) 
print(type(s1))
s1

<class 'numpy.ndarray'>


array([402, 358])

## # 1. 연습문제 - 게임 점수 데이터 분석 

In [29]:
Alpha = np.array([88, 92, 76, 100, 95, 81, 79, 98, 85, 87])

print("도수: ", len(Alpha))
print("평균:", np.average(Alpha))
print("표준편차:", np.std(Alpha))
print("최소값:", np.min(Alpha))
print("Numpy로 계산한 1사분위수:", np.quantile(Alpha, 0.25))
print("중앙값: ",np.median(Alpha))
print("Numpy로 계산한 3사분위수:", np.quantile(Alpha, 0.75))
print("최대값:", np.max(Alpha))


도수:  10
평균: 88.1
표준편차: 7.7
최소값: 76
Numpy로 계산한 1사분위수: 82.0
중앙값:  87.5
Numpy로 계산한 3사분위수: 94.25
최대값: 100


In [30]:
Bravo = np.array([65, 99, 78, 72, 80, 91, 75, 82, 89, 70])

print("도수: ", len(Bravo))
print("평균:", np.average(Bravo))
print("표준편차:", np.std(Bravo))
print("최소값:", np.min(Bravo))
print("Numpy로 계산한 1사분위수:", np.quantile(Bravo, 0.25))
print("중앙값: ",np.median(Bravo))
print("Numpy로 계산한 3사분위수:", np.quantile(Bravo, 0.75))
print("최대값:", np.max(Bravo))

도수:  10
평균: 80.1
표준편차: 9.924212815130478
최소값: 65
Numpy로 계산한 1사분위수: 72.75
중앙값:  79.0
Numpy로 계산한 3사분위수: 87.25
최대값: 99


## # 2. 연습문제 - 교통사고 발생량으로부터 인사이트 발견하기 

In [32]:
car = np.array([15129, 13836, 15738, 16300, 17605, 16690, 17000, 16956, 17720, 17455, 15668])

print("도수: ", len(car))
print("평균:", np.average(car))
print("표준편차:", np.std(car))
print("최소값:", np.min(car))
print("Numpy로 계산한 1사분위수:", np.quantile(car, 0.25))
print("중앙값: ",np.median(car))
print("Numpy로 계산한 3사분위수:", np.quantile(car, 0.75))
print("최대값:", np.max(car))



도수:  11
평균: 16372.454545454546
표준편차: 1137.2192851334078
최소값: 13836
Numpy로 계산한 1사분위수: 15703.0
중앙값:  16690.0
Numpy로 계산한 3사분위수: 17227.5
최대값: 17720


평균, 중앙값이 비슷하다. IQR의 범위가 크지 않다. 