# [LAB-02] 2. 다양한 ndarray 유형

## 연습문제 (1)

In [1]:
import numpy as np

# 1. 정수형 배열로 변환
score = [72.5, 88.0, 91.5, 67.0, 80.0, 59.5]
arr = np.array(score, dtype='int')
print("원본 점수:", arr)

# 2. 80점 이상 추출
over80 = arr[arr >= 80]
print("80점 이상:", over80)

# 3. 학점 부여 조건 설정
conditions = [
    (arr >= 90),
    (arr >= 80),
    (arr >= 70)
]
values = ['A', 'B', 'C']

# 4. np.select()로 학점 계산
grades = np.select(conditions, values, default='F')
print("학점 결과:", grades)

원본 점수: [72 88 91 67 80 59]
80점 이상: [88 91 80]
학점 결과: ['C' 'B' 'A' 'F' 'B' 'F']


## 연습문제 (2)

In [2]:
import numpy as np

# 1. 랜덤 시드 고정 및 정규분포 데이터 생성
np.random.seed(100)
scores = np.random.normal(75, 5, (3, 4))
print(scores)

# 2. 80점 이상인 값만 추출
over80 = scores[scores >= 80]
print("80점 이상 점수:", over80)

# 3. 배열의 속성 출력
print("차원:", scores.ndim)
print("형태:", scores.shape)
print("데이터 타입:", scores.dtype)

[[66.25117263 76.71340202 80.76517901 73.73781982]
 [79.90660393 77.57109421 76.10589835 69.64978335]
 [74.05252085 76.27500722 72.70986507 77.17581744]]
80점 이상 점수: [80.76517901]
차원: 2
형태: (3, 4)
데이터 타입: float64
