# [LAB-02] 3. ndarray 형태 변환

## 연습문제 

In [22]:
import numpy as np

# 1. 0~11 배열 생성
arr = np.arange(12)
print("원본 배열:", arr)

# 2. 실수형으로 변환
arr_float = arr.astype('float')
print("실수형 변환:", arr_float)

# 3. 2행 6열로 변환
arr_2x6 = arr_float.reshape(2, 6)
print("2행 6열 형태:")
print(arr_2x6)

# 4. 자동 계산을 이용한 n행 4열 변환
arr_nx4 = arr_float.reshape(-1, 4)
print("자동 계산된 형태(n행, 4열):")
print(arr_nx4)

# 5. 1차원으로 축소
arr_flat = arr_float.reshape(-1)
print("1차원 배열로 축소:")
print(arr_flat)

원본 배열: [ 0  1  2  3  4  5  6  7  8  9 10 11]
실수형 변환: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
2행 6열 형태:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]
자동 계산된 형태(n행, 4열):
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
1차원 배열로 축소:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
