# [LAB-02] 1. NumPy 시작하기

## # 01. 준비작업 

### 1. 라이브러리 참조하기 

In [2]:
# numpy 라이브러리를 np라는 이름으로 사용하도록 
import numpy as np

## #02. 배열 생성하기 

### 1. 리스트를 통한 1차원(=1행으로 구성) 배열 만들기 

- 리스트 자료형의 업그레이드 버전으로 리스트와 기본 특성이 동일하다. 
    - 인덱스 번호와 길이의 존재 인덱싱, 슬라이싱 / 반복문을 통한 원소의 탐색

In [3]:
# list를 파라미터로 전달하여 ndarray 생성
arr = np.array([1,3,5,7,9])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 3, 5, 7, 9])

In [4]:
arr = np.array([10,30,50,70,90])
size = len(arr)
print("배열의 원소는 %d개 입니다." % size)

배열의 원소는 5개 입니다.


In [5]:
mydata = np.array([5,10,15,20,25])

# 인덱싱을 사용한 원소의 접근
print(mydata[0])  # 첫 번째 원소
print(mydata[1])  # 두 번째 원소
print(mydata[3]) 

# 슬라이싱을 사용한 구간 추출 
print(mydata[1:4])
print(mydata[-4:-1])

5
10
20
[10 15 20]
[10 15 20]


In [6]:
mydata = np.array([100, 110, 120, 130, 140])

for i, v in enumerate(mydata):
    print("%d번째 원소 >> %d" % (i, v))

0번째 원소 >> 100
1번째 원소 >> 110
2번째 원소 >> 120
3번째 원소 >> 130
4번째 원소 >> 140


In [7]:
mylist = [100, 3.14, True]
mylist

[100, 3.14, True]

In [8]:
myarr = np.array(mylist)
myarr

array([100.  ,   3.14,   1.  ])

In [9]:
mylist1 = [100.12, 3.14, 1.5]
myarr1 = np.array(mylist1, dtype='int')
myarr1

array([100,   3,   1])

In [10]:
mylist2 = [1.2, 3, True, '4']
myarr2 = np.array(mylist2)
myarr2

array(['1.2', '3', 'True', '4'], dtype='<U32')

In [11]:
mylist3 = [10, 20, 30, 40, 50]
myarr3 = np.array(mylist3)
print(type(myarr3), myarr3)

mylist3_1 = list(myarr3)
print(type(mylist3_1), mylist3_1)

<class 'numpy.ndarray'> [10 20 30 40 50]
<class 'list'> [np.int64(10), np.int64(20), np.int64(30), np.int64(40), np.int64(50)]


In [12]:
# 1. 연산자 사용 -> 위치가 동일한 원소끼리 연산 
arr1 = np.array([10,15,20,25,30])
arr2 = np.array([2,3,4,5,6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [13]:
a = arr1 + arr2 
a

array([12, 18, 24, 30, 36])

In [14]:
b = arr1 - arr2
b

array([ 8, 12, 16, 20, 24])

In [15]:
c = arr1 * arr2 
c

array([ 20,  45,  80, 125, 180])

In [16]:
d = arr1 / arr2 
d

array([5., 5., 5., 5., 5.])

In [17]:
a = np.add(arr1, arr2)
a

array([12, 18, 24, 30, 36])

In [18]:
b = np.subtract(arr1, arr2)
b

array([ 8, 12, 16, 20, 24])

In [19]:
c = np.multiply(arr1, arr2)
c

array([ 20,  45,  80, 125, 180])

In [20]:
d = np.divide(arr1, arr2)
d

array([5., 5., 5., 5., 5.])

In [21]:
# 철수의 1학년 ~ 4학년까지의 평균 점수 
grade = np.array([82, 77, 91, 88])
grade

array([82, 77, 91, 88])

In [22]:
# -> 추출하고자 하는 원본과 같은 사이즈의 배열을 생성한다. 
# -> 추출할 값은 True, 그렇지 않으면 False 
bool_array = np.array([True, False, True, False])
bool_array

array([ True, False,  True, False])

In [23]:
# -> 조건에 맞는 항목만 1차 배열로 추출
result1 = grade[bool_array]
result1

array([82, 91])

In [24]:
# 80점 이상은 원소만 추출하기 
# -> 조건을 명시하기 위해 배열의 이름이 조건식에 명시된다.
mypoint = np.array([82, 77, 91, 88])
ge80 = mypoint[mypoint >= 80]
ge80

array([82, 91, 88])

In [25]:
ge80le90 = mypoint[np.logical_and(mypoint >=80, mypoint <=90)]
ge80le90

array([82, 88])

In [26]:
gt_or_lt = mypoint[np.logical_or(mypoint < 80, mypoint > 90)]
gt_or_lt

array([77, 91])

In [27]:
exam = np.array([60, 83, 75, 92, 86])

# 첫번째 파라미터로 주어진 조건이 참일 경우 '합격', 
# 그렇지 않은 경우 '불합격'
result = np.where(exam >=80, '합격', '불합격')
result

array(['불합격', '합격', '불합격', '합격', '합격'], dtype='<U3')

In [28]:
# 다중 조건 분기 
exam = np.array([60, 85, 51, 79, 94, 88])

# 학점을 부여하기 위한 점수의 구간을 설정하는 조건들을 리스트로 생성 
conditions = [(exam >=90), 
              (exam >=80),
              (exam >=70)]

# 조건에 따라 부여될 학점 
value = ['A', 'B', 'C']

# 조건과 조건을 판단하기 위한 값을 지정함 
# default는 조건에 맞는 값이 아닌 경우 사용됨 (생략가능)
result = np.select(conditions, value, default='F')
result 

array(['F', 'B', 'F', 'C', 'A', 'B'], dtype='<U1')

In [29]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])

print("배열의 길이:", len(a))

print("첫 번째 원소:", a[0])
print("마지막 원소 두개의 원소:", a[-1], a[-2])
print("마지막 두 개 원소:", a[-2:])

for i in range(len(a)):
    print(i, "번째 원소", a[i])

배열의 길이: 5
첫 번째 원소: 10
마지막 원소 두개의 원소: 50 40
마지막 두 개 원소: [40 50]
0 번째 원소 10
1 번째 원소 20
2 번째 원소 30
3 번째 원소 40
4 번째 원소 50


In [30]:
import numpy as np

# 1. 배열 생성
arr = np.array([10, 20, 30, 40, 50])

# 2. 배열의 길이 출력
print("배열의 길이:", len(arr))

# 3. 인덱싱 / 슬라이싱
print("첫 번째 원소:", arr[0])
print("마지막 두 개 원소:", arr[-2:])

# 4. 반복문 + enumerate
for i, v in enumerate(arr):
    print("%d번째 원소 >> %d" % (i, v))

배열의 길이: 5
첫 번째 원소: 10
마지막 두 개 원소: [40 50]
0번째 원소 >> 10
1번째 원소 >> 20
2번째 원소 >> 30
3번째 원소 >> 40
4번째 원소 >> 50


In [31]:
arr = np.array([1,3,5,7,9])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 3, 5, 7, 9])