# [LAB-02] 4. 기술 통계량의 이해 (1)

## #01. 준비작업

### 1. 라이브러리 참조

In [1]:
import numpy as np

### 2. 샘플 데이터 생성

In [2]:
myarr = np.array([98, 72, 80, 64, 88, 65, 79, 59, 81, 74])
myarr

array([98, 72, 80, 64, 88, 65, 79, 59, 81, 74])

## #02. 데이터의 위치·분포를 나타내는 기술 통계량

### 1. 총 도수

In [3]:
print("총 도수:", len(myarr))

총 도수: 10


### 2. 최대, 최소, 합계

In [4]:
print("최대값:", np.max(myarr))
print("최소값:", np.min(myarr))
print("합계:", np.sum(myarr))

최대값: 98
최소값: 59
합계: 760


### 3. 평균 ($\mu$)

- 모든 값을 더한 후 개수로 나눈 값
- 평균은 특정 값이 다른 값들의 범위와 차이가 큰 경우 신뢰도가 떨어진다.
  - 1, 2, 3, 4, 5, 100의 평균은 ((1+2+3+4+5+100))/6 이므로 19.17이다
  - 위의 데이터에서 100에 해당하는 값은 다른 값들에 비해 극단적으로 높다. 이러한 값을 극단치라고 한다.

- 평균은 제공되는 함수가 두 개 이다.

In [5]:
print("평균(average):", np.average(myarr))
print("평균(mean):", np.mean(myarr))

평균(average): 76.0
평균(mean): 76.0


### 4. 중앙값 (직접 구하기)

In [6]:
size = len(myarr)           # 전체 데이터 수
sorted_arr = np.sort(myarr) # 순서대로 정렬
print("정렬:", sorted_arr)

# 짝수인 경우 가운데 두 수의 평균
if size % 2 == 0:
    p = (size // 2) - 1 # 인덱스가 0부터 시작하므로 -1
    q = p + 1           # p번째 다음 요소의 인덱스
    median = (sorted_arr[p] + sorted_arr[q]) / 2
else:
    p = size // 2
    median = sorted_arr[p]

print("중앙값:", median)

정렬: [59 64 65 72 74 79 80 81 88 98]
중앙값: 76.5


### 5. 중앙값 (NumPy 사용)

In [7]:
print("중앙값:", np.median(myarr))

중앙값: 76.5


### 6. 1사분위 수

In [8]:
x = np.sort(myarr)          # 데이터 정렬
n = len(x)                  # 총 도수
q1_pos = (n - 1) * 0.25     # 위치 계산 (p)
i = int(np.floor(q1_pos))   # 아래쪽 인덱스(i)
f = q1_pos - i              # 보간비율(f)

# 보간(interpolation)
Q1 = x[i] + f * (x[i + 1] - x[i])
print("직접 계산한 1사분위수 (Q1):", Q1)

# numpy 내장 함수와 비교
print("Numpy로 계산한 1사분위수:", np.quantile(myarr, 0.25))

직접 계산한 1사분위수 (Q1): 66.75
Numpy로 계산한 1사분위수: 66.75


### 7. 3사분위 수

In [9]:
x = np.sort(myarr)          # 데이터 정렬
n = len(x)                  # 총 도수
q3_pos = (n - 1) * 0.75     # 위치 계산 (p)
i = int(np.floor(q3_pos))   # 아래쪽 인덱스(i)
f = q3_pos - i              # 보간비율(f)

# 보간(interpolation)
Q3 = x[i] + f * (x[i + 1] - x[i])
print("직접 계산한 3사분위수 (Q3):", Q3)

# numpy 내장 함수와 비교
print("Numpy로 계산한 3사분위수:", np.quantile(myarr, 0.75))

직접 계산한 3사분위수 (Q3): 80.75
Numpy로 계산한 3사분위수: 80.75


## #04. 데이터의 범위·산포를 나타내는 기술 통계량

### 1. 데이터 구간 (Range)

- 최대값과 최소값의 차이
- 데이터가 전체적으로 얼마나 넓게 분포되어 있는지 보여줌
- 전체 변동 폭(variability)을 빠르게 파악할 수 있지만, 이상치(outlier) 의 영향을 매우 크게 받음 
  - 예를 들어, 집값 데이터가 **[4억, 5억, 6억, 25억]** 이면,    
  **Range = 25 − 4 = 21**억이 되므로 한 개의 극단값 때문에 변동 폭이 과대평가됨


In [10]:
print("데이터 구간:", np.max(myarr) - np.min(myarr))

데이터 구간: 39


### 2. 사분위 수 구간(IQR)

- 3사분위수(Q3) 와 1사분위수(Q1) 의 차이
- 데이터의 중앙 50%가 분포하는 폭(데이터의 중심부(중앙 50%) 변동성)을 나타냄
- 이상치의 영향을 거의 받지 않아, 안정적인 산포 척도로 자주 사용됨
  - 예를 들어, [4, 5, 6, 25]에서
    - Q1 = 4.75, Q3 = 10.5 (대략적 보간 결과)
    - IQR = 10.5 − 4.75 = 5.75
    - 중심부 데이터는 4.75~10.5 사이에 집중되어 있음
    - Range(21)보다 훨씬 작아, 중심부의 안정된 분포를 보여줌


In [11]:
q3 = np.quantile(myarr, 0.75)
q1 = np.quantile(myarr, 0.25)
print("사분위수 구간(IQR):", q3 - q1)

사분위수 구간(IQR): 14.0


### 3. 분산, 표준편차

In [12]:
print("분산:", np.var(myarr))
print("표준편차:", np.std(myarr))

분산: 125.2
표준편차: 11.189280584559492


## #05. 2차원 배열의 기술 통계량

### 1. 각 열끼리 연산 (세로 연산)

- 2차원 배열은 연산을 수행할 방향에 대한 파라미터 axis를 설정해야 한다.

In [13]:
mydata = np.array([[98, 72, 80, 64, 88],
                   [65, 79, 59, 81, 74]])

s1 = np.sum(mydata, axis=0)
print(type(s1))
s1

<class 'numpy.ndarray'>


array([163, 151, 139, 145, 162])

### 2. 각 행끼리 더함 (가로 연산)

- 2차원 배열은 연산을 수행할 방향에 대한 파라미터 axis를 설정해야 한다.

In [14]:
mydata = np.array([[98, 72, 80, 64, 88],
                   [65, 79, 59, 81, 74]])

s2 = np.sum(mydata, axis=1)
print(type(s2))
s2

<class 'numpy.ndarray'>


array([402, 358])